/**
 * 女優データアイテム文字列
 */
export const ActorDataItemName = {
  Id:                 "id",
  Name:               "name",
  Password:           "password",
  Open:               "open",
  Type:               "type",
  IsAdmin:            "is_admin",
  IsDeleted:          "is_deleted",
  ActressName:        "actress_name",
  RealName:           "real_name",
  Birthday:           "birthday",
  BloodType:          "blood_type",
  Height:             "height",
  Weight:             "weight",
  ClothesSize:        "clothes_size",
  ShoesSize:          "shoes_size",
  BreastSize:         "breast_size",
  BreastTopSize:      "breast_top",
  BreastUnderSize:    "breast_under",
  WaistSize:          "waist_size",
  HipSize:            "hip_size",
  Honban:             "honban",
  Gomunashi:          "gomunashi",
  Nakadashi:          "nakadashi",
  Ferachio:           "ferachio",
  Iramachio:          "iramachio",
}

/**
 * 女優データアイテムの親アイテム文字列
 */
export const ActorDataItemParentName = {
  Id:                 "",
  Name:               "",
  Password:           "",
  Open:               "",
  Type:               "",
  IsAdmin:            "",
  IsDeleted:          "",
  ActressName:        "profile",
  RealName:           "profile",
  Birthday:           "profile",
  BloodType:          "profile",
  Height:             "profile",
  Weight:             "profile",
  ClothesSize:        "profile",
  ShoesSize:          "profile",
  BreastSize:         "profile",
  BreastTopSize:      "profile",
  BreastUnderSize:    "profile",
  WaistSize:          "profile",
  HipSize:            "profile",
  Honban:             "playCondition1",
  Gomunashi:          "playCondition1",
  Nakadashi:          "playCondition1",
  Ferachio:           "playCondition1",
  Iramachio:          "playCondition1",
}